package ios.map;

typedef MKFoundation = ios.map.MKFoundation;
typedef MKAnnotation = ios.map.MKAnnotation;
typedef MKAnnotationView = ios.map.MKAnnotationView;
typedef MKDirectionsRequest = ios.map.MKDirectionsRequest;
typedef MKGeometry = ios.map.MKGeometry;
typedef MKMapItem = ios.map.MKMapItem;
typedef MKMapView = ios.map.MKMapView;
typedef MKPinAnnotationView = ios.map.MKPinAnnotationView;
typedef MKPlacemark = ios.map.MKPlacemark;
typedef MKReverseGeocoder = ios.map.MKReverseGeocoder;
typedef MKUserLocation = ios.map.MKUserLocation;
typedef MKTypes = ios.map.MKTypes;
typedef MKOverlay = ios.map.MKOverlay;
typedef MKShape = ios.map.MKShape;
typedef MKPointAnnotation = ios.map.MKPointAnnotation;
typedef MKMultiPoint = ios.map.MKMultiPoint;
typedef MKPolyline = ios.map.MKPolyline;
typedef MKPolygon = ios.map.MKPolygon;
typedef MKCircle = ios.map.MKCircle;
typedef MKOverlayView = ios.map.MKOverlayView;
typedef MKOverlayPathView = ios.map.MKOverlayPathView;
typedef MKPolygonView = ios.map.MKPolygonView;
typedef MKPolylineView = ios.map.MKPolylineView;
typedef MKCircleView = ios.map.MKCircleView;
typedef MKUserTrackingBarButtonItem = ios.map.MKUserTrackingBarButtonItem;
